version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    environment:
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}

  filebeat:
    build: ./filebeat
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}

  spring-app:
    build: .
    image: my-spring-logging-app:latest
    ports:
      - "8080:8080"
    volumes:
      - ./path/on/host/to/spring/app/logs:/app/logs
